### ISSUE TITLE
Ability to sorting with dynamic SortableItem

### ISSUE THREAD

**Issue by larvata** [jasonslyvia/react-anything-sortable#15]
Sometimes, we not only sort the items but also wants add/remove items dynamically.
I think this feature is useful for some scenario, e.g. a todolist app.

I would be grateful to you if you could consider this request.

---

I have notice this issue seems duplicated with #6 
The given workaround that set the `key` property of `Sortable`, but it is inconvenience in some case.

If I sort the `list` [a,b,c,d] => [a,c,b,d] 
and append a element 'e' to the `list`
the `list` will be rendered as [a,b,c,d,e] because of the  was `_orderArr` reset
certainly, I can sort the list by `sortData` before `list.length` changed to workaround this.
But I still wonder what is the better way to solve this problem.

**Comment by jasonslyvia** [comment]
Hi @larvata, although my guts tell me there might be a way that giving every child a unique key and identify the addition or removal in side `Sortable` component which will solve your problem, I still believe it is more of a trade off for sorting `this.props.children` instead of some Array format props.

Anyway, I'll let you know if there is any update.

**Comment by jasonslyvia** [comment]
I added a dynamic demo, please check out if it suits your needs.

Demo: [http://jasonslyvia.github.io/react-anything-sortable/demo/index.html#react3](http://jasonslyvia.github.io/react-anything-sortable/demo/index.html#react3)

Code: [https://github.com/jasonslyvia/react-anything-sortable/blob/4e45d003173d80f5b2781720d67aec73669e59e0/demo/index.js#L57](https://github.com/jasonslyvia/react-anything-sortable/blob/4e45d003173d80f5b2781720d67aec73669e59e0/demo/index.js#L57)
