### ISSUE TITLE
Not working in touch enabled deviced

### ISSUE THREAD

**Issue by risonsimon** [jasonslyvia/react-anything-sortable#23]
This is not working in chrome. No elements are being dragged. I'm using Chrome v46.
I also tested it on firefox. It is working there.

**Comment by jasonslyvia** [comment]
Which version of `react-anything-sortable` are you using? Is there any error in console?

**Comment by risonsimon** [comment]
> Which version of react-anything-sortable are you using?

I used the [demo](http://jasonslyvia.github.io/react-anything-sortable/demo/index.html). 
I also cloned the repository and checked on my local machine too. 

>  Is there any error in console?

There are no errors in console.

**Comment by jasonslyvia** [comment]
That's weird.

I've tested it on Chrome 47 both Mac & Windows 7, even Chrome 31 in Windows 7, it renders properly.

Can you rule out any browser specific problem like extensions or something?

**Comment by risonsimon** [comment]
I tried in Chrome incognito mode with all plugins disabled. Still not working. 

Btw, I'm on Ubuntu 14.04.

**Comment by aduggleby** [comment]
Can confirm the current version does not work here on Windows 10, 64-bit, Chrome Version 47.0.2526.106 m (64-bit), started with no extensions and incognito.

Work on the same machine with FF and Edge.

**Comment by aduggleby** [comment]
I have done some more debugging it seems to the problem seems to appear only on touch enabled devices.

I was surprised that it was working in the exact same browser (down to the minor version) on the same OS but my main PC rather than my laptop where I first tested this.

After deactivating touch event in chrome (https://productforums.google.com/forum/#!topic/chrome/P1w9dhH_874) the library works in chrome on the laptop. Just when I reactive touch events (or rather set it to automatic) the library fails.

Does this help any further? Can I supply any other information?

@risonsimon Were you using a touch enabled device too?

**Comment by risonsimon** [comment]
That seems to make sense. I was using a touch enabled laptop too.

**Comment by jasonslyvia** [comment]
Thanks guys, I think the problem might be the way I determine whether should use `onmousedown` or `ontouchstart`. I will dig it.

**Comment by jasonslyvia** [comment]
It seems like when handling touch event, a wrong target is provided, so `react-anything-sortable` fails to calculate the new index of dragging item.

Please try the new demo to see if it works now.

http://jasonslyvia.github.io/react-anything-sortable/demo/index.html

**Comment by aduggleby** [comment]
No sadly doesn't work with clicks yet. Touch works as expected. I have cleared my cache and used icognito again.

**Comment by dev-mg** [comment]
I just debugged this issue. The expression ('ontouchstart' in window) always evaluates to false in desktop chrome, even with touch capabilities.

When I removed the if-else and defined all events anyway, it perfectly works for touch and non-touch in Chrome 48, for Chrome and Firefox on Android / Nexus 5, and still works for non-touch Firefox 38 ESR and IE11. There is some discussion that backs this approach is viable: http://www.stucox.com/blog/you-cant-detect-a-touchscreen/

Is there any special reason you implemented it that way? If so, Modernizr.touch feature detection would be useful - it also works for me.

You can also test yourself with Chrome Mobile Device Emulation if you don't have a touch device, see https://developer.chrome.com/devtools/docs/device-mode
I can send a pull request after clarifying which option you prefer.

**Comment by jasonslyvia** [comment]
@dev-mg  really appreciate your effort.

Frankly I'm not so familiar with touch-enabled devices/environment, so my guts tell me if `'ontouchstart' in window`, let's use `onTouchXXX` API, otherwise let's stick to `onMouseXXX`.

So if you're sure about listening both `onTouchXXX` and `onMouseXXX` event solves this issue, I'd like to merge your PR.

**Comment by jasonslyvia** [comment]
Hi, can you guys confirm whether it solves this problem or not by visiting [the demo](http://jasonslyvia.github.io/react-anything-sortable/demo/index.html) again? Really appreciate your effort!

**Comment by jasonslyvia** [comment]
If so, I will publish a new version to npm.

**Comment by aduggleby** [comment]
Hi, yes I can confirm it works (both touch and mouse)! Glad mg got it solved :)

**Comment by jasonslyvia** [comment]
Great, a new version will be released soon.

**Comment by risonsimon** [comment]
It works! Awesome.

**Comment by jasonslyvia** [comment]
`v1.3.6` released, thanks everyone.
