### ISSUE TITLE
Drag handle

### ISSUE THREAD

**Issue by szyablitsky** [jasonslyvia/react-anything-sortable#29]
Is it possible to add an ability to mark a drag handle inside of sortable item? This will allow to sort list only by dragging item with the handle, but not the whole item.

**Comment by jasonslyvia** [comment]
I'll consider adding this feature, meanwhile PRs are mostly welcome :)

**Comment by zthomas** [comment]
I made a quick PR as a feature proposal. 
https://github.com/jasonslyvia/react-anything-sortable/pull/33
It's working great for me right now, I had the same issue especially for mobile. 

@jasonslyvia this is just a proposal, feel free to change the syntax, it might be better to have it as a prop on the top level component instead of the sort element but I didn't want to change too much of your code.

**Comment by jasonslyvia** [comment]
Awesome, you're on fire @zthomas .
