### ISSUE TITLE
onMouseUp issue when clicked on draggable

### ISSUE THREAD

**Issue by ivdma** [jasonslyvia/react-anything-sortable#3]
The following line prevents handling onMouseUp when draggable element is clicked: https://github.com/jasonslyvia/react-anything-sortable/blob/master/Sortable.jsx#L143

For example we have a button on a draggable element. When button is pressed, pop-up appears. With that line, handleMouseUp returns on click (because mouse is not moving). So dragging is never cancelled.

I am not sure whether it's a bug or a feature. But if you consider this a feature, maybe you could make it a preference?

**Comment by jasonslyvia** [comment]
I believe that is a design on purpose to prevent some browser fire redundant mouse events, but I will inversigate it with next release.

**Comment by jasonslyvia** [comment]
Since I've refactored the code the aforementioned line should be [https://github.com/jasonslyvia/react-anything-sortable/blob/master/src/index.js#L152](https://github.com/jasonslyvia/react-anything-sortable/blob/master/src/index.js#L152).

Back to your scenario, if there's a button on a draggable element, how can you click it during dragging the element? 

So I believe this is the correct behaviour to make `handleMouseUp` respond only if `handleMouseDown` and `handleMouseMove`  have been called.

Please notice this `return` would cancel the event bubbling because 1) It ain't jQuery and 2) I didn't return false.

Let me know if there is anything I'm missing.

**Comment by ivdma** [comment]
> Back to your scenario, if there's a button on a draggable element, how can you click it during dragging the element?

My draggable elements are looking as follows: 

    [ Sortable A | x ]  [ Sortable B | x ]  [ Sortable C | x ]  [ Sortable D | x ]

User can push the `x` button (it's an actual <button>x</button>) when item is **not** dragging. This will trigger a bootstrap modal where user can set the reason why this item is being deleted.

Problem is: when I push the `x` button, it triggers `onMouseDown / handleMouseDown()`, which binds the drag event. 
When I release the mouse button `onMouseUp / handleMouseUp()` is called which is correct. 
But because the mouse did not move between `onMouseDown` and `onMouseUp`, `handleMouseUp()` returns immediately and thus never releases the drag event. So when I click `x` and move the mouse to a button on the modal, draggable element will move along with the mouse cursor.

The same behaviour still exists when I click the draggable element **outside** the `x` button. Latest Safari, Chrome, Firefox and IE8 on WinXP show the same behaviour.

**Comment by jasonslyvia** [comment]
I get your point, it turns out I add this `return` to prevent unnecessary `setState`. I'll fix in next release.

**Comment by ivdma** [comment]
Thanks!

**Comment by jasonslyvia** [comment]
Fixed in 529ee0d0af3b6d1ad139777db7a3a29482dc8a82

**Comment by milushov** [comment]
> Since I've refactored the code the aforementioned line should be https://github.com/jasonslyvia/react-anything-sortable/blob/master/src/index.js#L152.

btw, canonical url you can get by pressing `y`
